import sys
from py2neo import Graph, Node, Relationship

g = Graph(auth=(sys.argv[1],sys.argv[2]))
g.delete_all()

b1 = Node("Part",name="sparkplug",type="basic",price=10)
b2 = Node("Part",name="screw",type="basic",price=2)
b3 = Node("Part",name="gasket",type="basic",price=3)
b4 = Node("Part",name="bolt",type="basic",price=2)
g.create(b1)
g.create(b2)
g.create(b3)
g.create(b4)

c1 = Node("Part",name="engine",type="complex")
c2 = Node("Part",name="cylinder",type="complex")
c3 = Node("Part",name="valve",type="complex")
c4 = Node("Part",name="crankshaft",type="complex")
c5 = Node("Part",name="piston",type="complex")
c6 = Node("Part",name="connectingrod",type="complex")
c7 = Node("Part",name="hanger",type="complex")
c8 = Node("Part",name="joint",type="complex")
g.create(c1)
g.create(c2)
g.create(c3)
g.create(c4)
g.create(c5)
g.create(c6)
g.create(c7)
g.create(c8)

r1 = Relationship(c1,"subpart",b1,qty=4)
r2 = Relationship(c1,"subpart",c2,qty=4)
r3 = Relationship(c1,"subpart",c3,qty=4)
r4 = Relationship(c1,"subpart",c4,qty=1)
r5 = Relationship(c2,"subpart",c5,qty=1)
r6 = Relationship(c2,"subpart",c6,qty=1)
r7 = Relationship(c3,"subpart",b3,qty=1)
r8 = Relationship(c3,"subpart",c7,qty=2)
r9 = Relationship(c4,"subpart",c8,qty=8)
r10 = Relationship(c5,"subpart",b2,qty=2)
r11 = Relationship(c5,"subpart",b3,qty=3)
r12 = Relationship(c6,"subpart",b2,qty=4)
r13 = Relationship(c6,"subpart",b4,qty=4)
r14 = Relationship(c7,"subpart",b2,qty=4)
r15 = Relationship(c7,"subpart",b4,qty=2)
r16 = Relationship(c8,"subpart",b2,qty=10)
r17 = Relationship(c8,"subpart",b4,qty=20)
g.create(r1)
g.create(r2)
g.create(r3)
g.create(r4)
g.create(r5)
g.create(r6)
g.create(r7)
g.create(r8)
g.create(r9)
g.create(r10)
g.create(r11)
g.create(r12)
g.create(r13)
g.create(r14)
g.create(r15)
g.create(r16)
g.create(r17)
